"""
AlertStreamlit.py – Online Structural Monitoring Dashboard
-----------------------------------------------------------
Reads XML alert records generated by Alert.py and displays an interactive
monitoring dashboard suitable for hosting on Streamlit Cloud / any server.

Usage:
    streamlit run AlertStreamlit.py

Dependencies (all installable via pip):
    streamlit
    pandas
    plotly
"""

from __future__ import annotations

import io
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
from typing import List

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Structural Alert Monitor",
    page_icon="🏗️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Constants ─────────────────────────────────────────────────────────────────
ALERT_DIR = Path("alert_records")

LEVEL_COLORS = {
    "Warning":  "#ffaa44",
    "Critical": "#ff6b7a",
}

THEME_BG    = "#1e2130"
THEME_MID   = "#252a3d"
THEME_ACC   = "#4a9eff"
THEME_GREEN = "#4ddd88"
THEME_TEXT  = "#e8eaf0"

# ── Custom CSS / dark styling ─────────────────────────────────────────────────
st.markdown(
    """
    <style>
    /* Dark page background */
    html, body, [data-testid="stAppViewContainer"], [data-testid="stMain"] {
        background-color: #1e2130 !important;
        color: #e8eaf0 !important;
    }
    [data-testid="stSidebar"] {
        background-color: #16192b !important;
    }
    /* Metric cards */
    [data-testid="metric-container"] {
        background-color: #252a3d;
        border: 1px solid #3a4060;
        border-radius: 10px;
        padding: 14px 18px;
    }
    [data-testid="metric-container"] label {
        color: #9aa0b8 !important;
        font-size: 0.82rem;
    }
    [data-testid="metric-container"] [data-testid="stMetricValue"] {
        color: #4a9eff !important;
        font-size: 1.8rem;
        font-weight: 700;
    }
    div.stButton > button {
        background-color: #4a9eff;
        color: white;
        border: none;
        border-radius: 6px;
        padding: 0.4rem 1.2rem;
        font-weight: 600;
    }
    div.stButton > button:hover {
        background-color: #2d7de8;
    }
    /* Headers */
    h1, h2, h3, h4 { color: #e8eaf0 !important; }
    </style>
    """,
    unsafe_allow_html=True,
)


# ══════════════════════════════════════════════════════════════════════════════
# XML parsing
# ══════════════════════════════════════════════════════════════════════════════

def parse_xml(xml_bytes: bytes | str) -> List[dict]:
    """Parse XML alert file and return a flat list of violation dicts."""
    records: List[dict] = []
    try:
        if isinstance(xml_bytes, bytes):
            root = ET.fromstring(xml_bytes.decode("utf-8", errors="replace"))
        else:
            tree = ET.parse(str(xml_bytes))
            root = tree.getroot()

        project = root.attrib.get("project", "Unknown")
        for ev in root.findall("event"):
            ts    = ev.attrib.get("timestamp", "")
            cycle = ev.attrib.get("cycle", "")
            for v in ev.findall("violation"):
                records.append({
                    "project"    : project,
                    "timestamp"  : ts,
                    "cycle"      : int(cycle) if cycle.isdigit() else 0,
                    "rule"       : v.attrib.get("rule", ""),
                    "sensor"     : v.attrib.get("sensor", ""),
                    "dimension"  : v.attrib.get("dimension", ""),
                    "max_value"  : float(v.attrib.get("max_value", 0)),
                    "threshold"  : float(v.attrib.get("threshold", 0)),
                    "operator"   : v.attrib.get("operator", ">="),
                    "alert_level": v.attrib.get("alert_level", "Warning"),
                })
    except Exception as exc:
        st.error(f"Failed to parse XML: {exc}")
    return records


def load_df(records: List[dict]) -> pd.DataFrame:
    if not records:
        return pd.DataFrame()
    df = pd.DataFrame(records)
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce", utc=True)
    df["date"]      = df["timestamp"].dt.date
    df["hour"]      = df["timestamp"].dt.hour
    return df.sort_values("timestamp").reset_index(drop=True)


# ══════════════════════════════════════════════════════════════════════════════
# Sidebar – data source
# ══════════════════════════════════════════════════════════════════════════════

with st.sidebar:
    st.markdown("## 🏗️ Alert Monitor")
    st.markdown("---")

    source = st.radio(
        "Data Source",
        ["Upload XML file", "Local alert_records/"],
        index=0,
    )

    records: List[dict] = []

    if source == "Upload XML file":
        uploaded = st.file_uploader(
            "Upload an alert XML file",
            type=["xml"],
            accept_multiple_files=False,
        )
        if uploaded is not None:
            records = parse_xml(uploaded.read())

    else:  # Local directory
        if ALERT_DIR.exists():
            xml_files = sorted(ALERT_DIR.glob("*.xml"), key=lambda p: p.stat().st_mtime, reverse=True)
            if xml_files:
                selected = st.selectbox(
                    "Choose file",
                    options=xml_files,
                    format_func=lambda p: p.name,
                )
                if selected:
                    records = parse_xml(selected)
            else:
                st.warning("No XML files found in alert_records/")
        else:
            st.warning(
                "alert_records/ folder not found.  "
                "Run the Alert Monitor desktop app first to generate files."
            )

    st.markdown("---")

    df_full = load_df(records)

    st.info(f"**{len(records)}** violation records loaded")

    # ── Filters ───────────────────────────────────────────────────────────────
    if not df_full.empty:
        st.markdown("### Filters")

        all_sensors = sorted(df_full["sensor"].unique())
        sel_sensors = st.multiselect("Sensors", all_sensors, default=all_sensors)

        all_dims = sorted(df_full["dimension"].unique())
        sel_dims = st.multiselect("Dimensions", all_dims, default=all_dims)

        all_levels = sorted(df_full["alert_level"].unique())
        sel_levels = st.multiselect("Alert Level", all_levels, default=all_levels)

        date_min = df_full["date"].min()
        date_max = df_full["date"].max()
        if date_min != date_max:
            date_range = st.date_input(
                "Date range",
                value=(date_min, date_max),
                min_value=date_min,
                max_value=date_max,
            )
            if isinstance(date_range, (list, tuple)) and len(date_range) == 2:
                d0, d1 = date_range
            else:
                d0, d1 = date_min, date_max
        else:
            d0, d1 = date_min, date_max

        mask = (
            df_full["sensor"].isin(sel_sensors) &
            df_full["dimension"].isin(sel_dims) &
            df_full["alert_level"].isin(sel_levels) &
            (df_full["date"] >= d0) &
            (df_full["date"] <= d1)
        )
        df = df_full[mask].copy()
    else:
        df = df_full


# ══════════════════════════════════════════════════════════════════════════════
# Main content
# ══════════════════════════════════════════════════════════════════════════════

st.title("🏗️ Structural Monitoring – Alert Dashboard")

if df.empty:
    st.info("👈 Load an XML file from the sidebar to get started.")
    st.stop()

# ── KPI row ───────────────────────────────────────────────────────────────────
n_events    = df["cycle"].nunique()
n_violations= len(df)
n_critical  = int((df["alert_level"] == "Critical").sum())
pct_crit    = f"{100*n_critical/n_violations:.1f}%" if n_violations else "0%"
n_sensors   = df["sensor"].nunique()

project_name = df["project"].iloc[0] if "project" in df.columns else "–"

if not df["timestamp"].isna().all():
    ts_min = df["timestamp"].dropna().min().strftime("%Y-%m-%d %H:%M")
    ts_max = df["timestamp"].dropna().max().strftime("%Y-%m-%d %H:%M")
    date_range_str = f"{ts_min}  →  {ts_max}"
else:
    date_range_str = "–"

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Project",     project_name)
col2.metric("Alert Events",  f"{n_events}")
col3.metric("Total Violations", f"{n_violations}")
col4.metric("Critical",    f"{n_critical}  ({pct_crit})")
col5.metric("Sensors",     f"{n_sensors}")

st.caption(f"🕒 Date range: {date_range_str}")
st.markdown("---")

# ── Stem chart – violations over time ─────────────────────────────────────────
st.subheader("📊 Violations Over Time (Stem Chart)")

# Build a time-indexed series: count violations per cycle per sensor+dim
df_stem = df.copy()
df_stem["key"] = df_stem["sensor"] + " / " + df_stem["dimension"]
df_stem = df_stem.sort_values("timestamp")

# Use cycle or sequential index as x-axis
df_stem["index"] = range(len(df_stem))

unique_keys = df_stem["key"].unique()
stem_colors = px.colors.qualitative.D3

stem_fig = go.Figure()
for i, key in enumerate(unique_keys):
    sub = df_stem[df_stem["key"] == key]
    color = stem_colors[i % len(stem_colors)]
    # Stem: vertical lines from baseline to value, with marker on top
    for _, row in sub.iterrows():
        stem_fig.add_trace(go.Scatter(
            x=[row["index"], row["index"]],
            y=[0, row["max_value"]],
            mode="lines",
            line=dict(color=color, width=1.5),
            showlegend=False,
            hoverinfo="skip",
        ))
    # Markers (one per data point — shown in legend)
    stem_fig.add_trace(go.Scatter(
        x=sub["index"],
        y=sub["max_value"],
        mode="markers",
        name=key,
        marker=dict(size=8, color=color),
        hovertemplate=(
            f"<b>{key}</b><br>"
            "Value: %{y:.5f}<br>"
            "Cycle: %{customdata[0]}<br>"
            "Level: %{customdata[1]}<br>"
            "Time: %{customdata[2]}<extra></extra>"
        ),
        customdata=sub[["cycle", "alert_level", "timestamp"]].values,
    ))

# Threshold lines per rule
for rule_name, rule_df in df_stem.groupby("rule"):
    thr = rule_df["threshold"].iloc[0]
    level = rule_df["alert_level"].iloc[0]
    line_color = LEVEL_COLORS.get(level, "#ffaa44")
    stem_fig.add_hline(
        y=thr,
        line_dash="dash",
        line_color=line_color,
        line_width=1.5,
        annotation_text=f"{rule_name} ({thr:.4g})",
        annotation_font_color=line_color,
        annotation_font_size=10,
    )

stem_fig.update_layout(
    paper_bgcolor=THEME_BG,
    plot_bgcolor=THEME_MID,
    font=dict(color=THEME_TEXT, size=11),
    legend=dict(bgcolor=THEME_MID, bordercolor="#3a4060", borderwidth=1),
    xaxis=dict(
        title="Alert Index",
        gridcolor="#3a4060",
        zerolinecolor="#3a4060",
    ),
    yaxis=dict(
        title="Max Absolute Value",
        gridcolor="#3a4060",
        zerolinecolor="#3a4060",
    ),
    margin=dict(l=60, r=20, t=30, b=50),
    height=420,
)
st.plotly_chart(stem_fig, use_container_width=True)

# ── Row: pie + bar ────────────────────────────────────────────────────────────
st.markdown("---")
left_col, right_col = st.columns([1, 2])

with left_col:
    st.subheader("🥧 Alert Level Breakdown")
    pie_counts = df["alert_level"].value_counts()
    pie_fig = go.Figure(go.Pie(
        labels=pie_counts.index.tolist(),
        values=pie_counts.values.tolist(),
        marker=dict(colors=[LEVEL_COLORS.get(l, THEME_ACC) for l in pie_counts.index],
                    line=dict(color=THEME_BG, width=2)),
        textinfo="label+percent",
        textfont=dict(color=THEME_TEXT, size=12),
        hovertemplate="%{label}: %{value} (%{percent})<extra></extra>",
    ))
    pie_fig.update_layout(
        paper_bgcolor=THEME_BG,
        font=dict(color=THEME_TEXT),
        showlegend=False,
        margin=dict(l=10, r=10, t=10, b=10),
        height=280,
    )
    st.plotly_chart(pie_fig, use_container_width=True)

with right_col:
    st.subheader("📈 Violations by Sensor")
    bar_df = (
        df.groupby(["sensor", "alert_level"])
          .size()
          .reset_index(name="count")
    )
    bar_fig = px.bar(
        bar_df, x="sensor", y="count", color="alert_level",
        color_discrete_map=LEVEL_COLORS,
        labels={"count": "Violations", "sensor": "Sensor", "alert_level": "Level"},
        template="plotly_dark",
    )
    bar_fig.update_layout(
        paper_bgcolor=THEME_BG,
        plot_bgcolor=THEME_MID,
        font=dict(color=THEME_TEXT, size=11),
        legend=dict(bgcolor=THEME_MID, bordercolor="#3a4060", borderwidth=1,
                    title_text="Level"),
        xaxis=dict(gridcolor="#3a4060"),
        yaxis=dict(gridcolor="#3a4060"),
        margin=dict(l=40, r=10, t=20, b=50),
        height=280,
    )
    st.plotly_chart(bar_fig, use_container_width=True)

# ── Violations Over Days heatmap ──────────────────────────────────────────────
if df["date"].nunique() > 1:
    st.markdown("---")
    st.subheader("📅 Daily Violations Heatmap")
    heat_df = (
        df.groupby(["date", "alert_level"])
          .size()
          .reset_index(name="count")
    )
    heat_fig = px.bar(
        heat_df, x="date", y="count", color="alert_level",
        color_discrete_map=LEVEL_COLORS,
        labels={"count": "Violations", "date": "Date", "alert_level": "Level"},
        template="plotly_dark",
    )
    heat_fig.update_layout(
        paper_bgcolor=THEME_BG,
        plot_bgcolor=THEME_MID,
        font=dict(color=THEME_TEXT, size=11),
        legend=dict(bgcolor=THEME_MID, bordercolor="#3a4060", title_text="Level"),
        xaxis=dict(gridcolor="#3a4060"),
        yaxis=dict(gridcolor="#3a4060"),
        margin=dict(l=40, r=10, t=20, b=50),
        height=280,
    )
    st.plotly_chart(heat_fig, use_container_width=True)

# ── Data table ────────────────────────────────────────────────────────────────
st.markdown("---")
st.subheader("📋 Violation Records")

show_cols = [
    "timestamp", "cycle", "sensor", "dimension",
    "rule", "max_value", "threshold", "operator", "alert_level",
]
display_df = df[[c for c in show_cols if c in df.columns]].copy()
display_df["timestamp"] = display_df["timestamp"].dt.strftime("%Y-%m-%d %H:%M:%S %Z")
display_df["max_value"] = display_df["max_value"].map("{:.6f}".format)
display_df["threshold"] = display_df["threshold"].map("{:.6f}".format)

# Colour the alert_level column via pandas Styler
def _level_color(val: str) -> str:
    if val == "Critical":
        return "color: #ff6b7a; font-weight: bold"
    if val == "Warning":
        return "color: #ffaa44; font-weight: bold"
    return ""

styled = display_df.style.applymap(_level_color, subset=["alert_level"])
st.dataframe(styled, use_container_width=True, height=400)

# ── CSV download ──────────────────────────────────────────────────────────────
csv_buf = io.StringIO()
display_df.to_csv(csv_buf, index=False)
st.download_button(
    label="⬇️  Download as CSV",
    data=csv_buf.getvalue().encode("utf-8"),
    file_name=f"alert_violations_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
    mime="text/csv",
)

# ── Footer ────────────────────────────────────────────────────────────────────
st.markdown("---")
st.caption("Structural Monitoring Alert Dashboard  |  Powered by Streamlit + Plotly")
